### ISSUE TITLE
[CNCF] Review CNCF Services

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/community#10]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) that this issue will track:*

* [ ] *Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/*

**Comment by fitzthum** [comment]
I have looked through the [CNCF services overview page](https://www.cncf.io/services-for-projects/). I will list the things that seem the most notable to me at the moment. Please take a minute to do the same. This is not an exhaustive overview of the services page, which is not an exhaustive listing of the services that the CNCF offers. Note that prioritization and availability of some services might be different for sandbox projects. 

Program Management
* **Project governance creation and advice** See #9 
* **3rd Party Security Audits** Given that security is one of our main focuses, we might want to look into this at some point.

Tools
* **Zoom** Move weekly meetings to CNCF Zoom?
* **Slack** Move to CNCF workspace.
* **HackerOne** It might be cool to have bug bounties once the project is more mature.

The tools section does not mention website hosting, which is something we might need, but the **Technical Documentation** section alludes to hosting services.

Other
* **CI** CNCF offers some level of support for CI. We should keep this on the radar. @wainersm 
* **Events** There are a wide variety of ways to get project exposure via CNCF events. How can we expand our existing presence?
* **Marketing** Similarly there are variety of resources and guidelines for marketing. Some initiatives are mainly aimed at more mature projects, but there are definitely things we can take advantage of. @ariel-adam

**Comment by dcmiddle** [comment]
I don't see anything about a mail list for the project. Just a cncf-wide maintainers list.
A mail list seems like a basic service; did I miss it somewhere?

**Comment by fitzthum** [comment]
The CNCF does appear to [host lists](https://lists.cncf.io/g/main/subgroups). Currently we use the kata list to send meeting reminders, which people may or may not read. We could probably get a CNCF mailing list. Alternatively, we could move those announcements over to Slack, where most of our discussion happens. It's possible that we don't actually need a mailing list. Maybe lists aren't on the services page because they aren't as popular?

**Comment by magowan** [comment]
Yes If we have slack with reasonable history length do we need slack? I guess is slack not as easy for some?
In terms of moving across I guess we also need to be open with kata community.
We don't want to suddenly vanish nor do we want to use resources that are essentially for other purposes (different governing body, different project?) Kind of applies beyond zoom and slack I guess.

On flip side to joining CNCF then anyone looking for us who is already in CNCF will use standard CNCF project tools/services to find us?

And third angle on it all, since Kata is important to us, what would a 3rd party security audit cover? Would that include kata as part of a stack?

**Comment by larrydewey** [comment]
### Mailing Lists:
From my experience, mailing lists tend to provide a bit more of a guaranteed longevity. While slack is an interesting real-time communication solution, it hasn't yet been proven to be a great solution for archiving conversation threads. At the same time, though, many mailing lists have traditionally been used to keep track of upstream work for a project, and where Kata/CC is very heavily integrated into Github, a mailing list would not provide much of a benefit in that regard. The large elephant in the room, though, is there are many individuals not using Slack as their communication platform. Currently, Slack requires you to have an account, and does not provide a means for outsiders to collaborate with those inside of it. A mailing list could provide a means for individuals, unwilling or unable to use Slack, to become active contributors in the project. I would think the more contributors we get, the better, so I would see this as being a natural next step. However, I think defining the projects scope for the mailing list would be necessary, as well.

After re-reading this, I guess to clarify, I am definitely not proposing we migrate away from Slack. Slack likely isn't going anywhere. Just my views on the possible benefits of introducing a Mailing List.

### CNCF Zoom:
As soon as the press release occurs, I see an immediate benefit in merging into our meetings to using the CNCF owned and managed zoom instances. I can see interested individuals expecting a CNCF project to be associated with CNCF resources.

### Events:
I am extremely excited about possible events built around the project. It would be fantastic to meet with everyone in-person, and also to help build even more excitement around adoption of the project. What do we think this would look like? Would it be members of the board attending CNCF events? Would it be more focused around individuals representing CC through submitting talks, etc? 

### Marketing:
Although CC is very young, getting the word out to end-users will be extremely important. Should we create an issue to keep track of the organizations strategy and possible marketing targets?

### L10N/I18N:
Does the project have any plans for moving forward with localization and internationalization? I expect this will naturally come up at some point in the future (if it hasn't already).

**Comment by fitzthum** [comment]
@larrydewey 

The CNCF has mailing lists. I guess it can't hurt to make one. There is maybe some concern about discussion becoming fractured if we have too many places to communicate, but we currently have a slack and a list and it isn't an issue (although technically we don't have a CC-specific list). 

I agree that we should switch to the CNCF zoom. I'm not entirely sure where our current zoom comes from. We should definitely try to leverage the marketing and events opportunities. I am not sure what our plan for localization is. Does Kata do anything for this?

**Comment by bpradipt** [comment]
Reviewed the services list and the only thing I find missing is the ability to create a mailing list/google-group. Based on the previous comment from @fitzthum looks like it is possible to create one and we can create a CC specific list going forward.

**Comment by fidencio** [comment]
From my side, let me only mention things that were not mentioned here yet.

Tools:
[LastPass](https://www.lastpass.com/), [1Password](https://github.com/1Password/1password-teams-open-source) and [Keybase](https://keybase.io/) to manage to shared secrets -- as it's been proven from the Kata Containers side that we need to find a reasonable way to give access to secrets to a certain amount of members of the community, so we have capable people with enough rights covering all time zones.

Technical Documentation, we know how hard it's to get it hard and to keep it up-to-date.  If we can rely on CNCF to provide any help, better.

Continuous Integration, as an integration project we should rely on our own CI to test all the bits and pieces together.  For instance, containerd has their CI, Kata Containers has their CI, image-rs will have their own CI.  But we'll need to test those integrated on our side.  I know @fitzthum mentiones this on his "Others" but, to me, this is a huge one. :-)

Marketing:
Case Studies is a huge thing to show how the project is being used and by who.  It's amazing their marketing team could help us to have those done, and those then can be used for the time when we think about / apply for graduation

Surveys:
This is something we struggled a lot with in the past, to get one done, to have it updated, and to get its results.  Having CNCF being able to help is also a huge plus.

Yeah, the list of service they provide is really good! :-)

**Comment by peterzcst** [comment]
I have read the page of https://www.cncf.io/services-for-projects/. 

+1 to create a mailing list for CC
Not sure where CNCF supported zoom mean. But at least we might be able to change current password for weekly meeting as "CC", rather than kata.

**Comment by fitzthum** [comment]
Ok, thanks everyone for reviewing this. I think some of these services will be useful in the short term, like Slack, Zoom, etc. Others are inevitably going to be important in the next phase of the projects, like CI stuff. There are also some that we will need to be proactive about taking advantage of, like PR and Events stuff.

I am going to close this for now, but feel free to reopen if you have further comment.
