### ISSUE TITLE
[CNCF] CNCF Code of Conduct 

### ISSUE THREAD

**Issue by dcmiddle** [confidential-containers/community#11]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) that this issue will track:*

* GitHub: ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub

**Comment by ariel-adam** [comment]
Dan, what remains to converge this issue?

**Comment by dcmiddle** [comment]
@ariel-adam this PR is stuck. https://github.com/confidential-containers/.github/pull/7
@sameo and @magowan asked for adding lines to the README. That has been added. Subsequently @fitzthum considers that unnecessary given his later PR. And there may be remaining confusion to discuss on how the README in a .github repo functions. (Though I added clarifications and references in the PR).
