### ISSUE TITLE
[CNCF] CII Best Practices Badge

### ISSUE THREAD

**Issue by dcmiddle** [confidential-containers/community#12]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/sandbox/issues/216) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/sandbox/issues/216) that this issue will track:*

* [ ] _CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en_

**Comment by dcmiddle** [comment]
The CII Best Practices badge is meant to help maintainers be conscious if not fulfill security best practices. 
It needs to be started as a team in a live discussion - probably one of our thursday sessions. Typically it takes more than 1 full session to complete. We aren't required to immediately complete the badge (which could take months to satisfy certain criteria) but we do need to get a solid start.  This probably means consuming the bulk of one of the next ~3 meetings in order to make the 1 month CNCF deadline.

**Comment by dcmiddle** [comment]
I initiated the badge process. I will fill in some of the boilerplate material directly, but most of this should be discussed in the community meeting.
https://bestpractices.coreinfrastructure.org/en/projects/5719

**Comment by fitzthum** [comment]
Planning to discuss during community meeting on the 31st. As you say, we definitely won't be able to complete all of the requirements before onboarding, but these seem like very thorough guidelines that will benefit the project and overlap significantly with requirements for incubation.

**Comment by fitzthum** [comment]
@dcmiddle I thought you had a conflict on the 24th?

**Comment by peterzcst** [comment]
Reviews.

**Comment by ariel-adam** [comment]
Dan, what remains to do on this issue?

**Comment by dcmiddle** [comment]
Labeled issues: https://github.com/confidential-containers/community/issues?q=is%3Aissue+is%3Aopen+label%3Asecurity-badge

**Comment by ariel-adam** [comment]
@dcmiddle is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?
