### ISSUE TITLE
[CNCF] Website-related onboarding

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/community#13]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) that this issue will track:*

* [ ] *Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63*
* [ ] *Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).*
* [ ] *Website: Analytics transferred to [amye@linuxfoundation.org](mailto:amye@linuxfoundation.org)*

**Comment by fitzthum** [comment]
We don't have a website. This either means that we can skip these things (except putting the LF footer in the READMEs) or that we should make a website. We will definitely want to have a website at some point. Is now the time to make it? How would we go about designing and hosting it? What is the purpose of a project website?

**Comment by jodh-intel** [comment]
# Site

+1 to creating a website. I think we need this asap personally. We could start with a simple [GH pages](https://pages.github.com) solution as it's static, uses markdown files and is self-managing.

# User categories

> What is the purpose of a project website?

To answer that, I think we need to define some categories of users along with a list of common questions that each group may have.

> **Note:** The following is just a quick dump so I'm sure it will need tweaking!

## Interested parties

### Manager / architect / consultant / CTO

**Requirement:** I want to understand CC.

We'll need a high level overview for understanding and initial evaluation (slides, white papers, overview diagrams, _etc_)

Common questions:

- What is CC?
- Why is CC relevant/compelling?
- Who is supporting / already contributing to this project?
- What are the goals of the project?
- What is the current state of the project?
- When will it release it's 1.0?
- What policies and standards does CC use?
- What does the project plan to do in the next 'n' months/years?
- How does CC interoperate with my environment?
- What are the requirements to start using CC?
- Are there any demos available?
- Where do I go to get answers to any others questions I may have?

## Users

### Devops / administrators

**Requirement:** I want to understand and install CC.

Common questions:

- What is CC?
- What are the h/w requirements?
- How can I install it?
- How can I manage/monitor/upgrade it?

## Contributors

### General contributor

**Requirement:** I want to understand and contribute to CC.

Common questions:

- What is CC?
- How can I participate?

### Specific contributors

#### Developer

**Requirement:** I want to understand CC and start hacking on the code.

Common questions:

- What is CC?
- How can I get the code?
- How can I build the code?
- How can I test the code?
- How can I debug the code?
	
#### Tester

**Requirement:** I want to understand CC and start stressing the code.

Common questions:

- What is CC?
- How do I install CC?
- Where are the tests?
- How do I run the tests?
- Where is the CI dashboard?
- How do I debug test failures?
- How do I write new tests?

#### Packager
	
**Requirement:** I want to understand CC and be able to package the code.

Common questions:

- What is CC?
- What packaging formats are appropriate?
- Are there any packaging tools?

#### Documentation contributor / technical writer

**Requirement:** I want to understand CC and be able to explain the code.

Common questions:

- What is CC?
- Where are the docs?
- What format are docs in?
- What doc conventions are used?
- What doc tooling is available?

#### Web developer

**Requirement:** I want to understand CC and be able to change the web site.

- What is CC?
- Where are the website sources?
- How can I test my changes locally?

# Role of the public website

GitHub is designed for contributors. That implies we need the public website for the other user categories, namely for Interested Parties and Users. Hence:

- The web site should:
  - Explain CC at a high level.
  - Provide answers to the sorts of questions posed by
    - Interested Parties
    - Users
  - Provide links for potential contributors (probably to in-tree material).

- The GitHub repos will be mostly "consumed" by contributors

  Although some of the links on the public website will no doubt link
  through to in-tree docs in the various repos.

**Comment by ariel-adam** [comment]
If we decide to go with a website who can take the lead on creating it :-) ?

**Comment by ariel-adam** [comment]
Closed it by mistake, multi tasking kills...

**Comment by ariel-adam** [comment]
We agree at this point not to create a website and if someone else will volunteer to create it later on we will work with them

**Comment by fitzthum** [comment]
Reopening this because we need to add the LF footer to our README. Also, I think it might be worth discussing a bit more about the website plans although we could potentially do that on another issue.

**Comment by fitzthum** [comment]
Ok, since we've merged https://github.com/confidential-containers/.github/pull/9 I think we can close this.

I will make a new issue about making a website once we are done with onboarding.
