### ISSUE TITLE
[CNCF] Review Project Proposal Process

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/community#15]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) that this issue will track:*

* [ ] *Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction*

**Comment by fitzthum** [comment]
Although this task might not seem that exciting and probably does not require any immediate technical or organizational work, I think it's actually one of the most important pieces of the onboarding process because it helps us understand what the next steps for the project are. 

So what are the next steps? Well the big one is to become a CNCF incubating project. This seems like the obvious goal for our project. Becoming an incubating project is much more difficult than becoming a sandbox project. For detailed information about the requirements, check out the document linked in the issue. Here are a few highlights. First, incubating projects need a sponsor from the CNCF TOC. Second, projects are subjected to an extensive due diligence process in which representatives of the TOC evaluate the technical merit of the project, among other things. We should expect the due diligence process alone to take at least a few months. Then, there are the actual requirements for becoming an incubating project.

The full requirements for incubation are available [here](https://github.com/cncf/toc/blob/main/process/graduation_criteria.adoc#incubating-stage). A brief summary is that we need to continue growing the community with more people and more contributions. We also need a clear versioning scheme, a process for handling security issues, and perhaps most importantly, adopters. As we have discussed in our weekly meeting, adopters should be endusers, which excludes CSPs.

Let's try to keep these requirements in mind and think about how we can best meet them.

**Comment by ariel-adam** [comment]
Reviewed

**Comment by bpradipt** [comment]
Reviewed the requirements for different stage of the project. Agree it's important to keep the requirements in mind as we make progress.

**Comment by fidencio** [comment]
Reviewed.

**Comment by peterzcst** [comment]
Reviewed. 

We can start from versioning scheme definition and start discussion for handling security issues

For adopters, it's most challenging. We can do a lot of things like: 1. Moving CC towards a high quality E2E stack 2. Bring typical usages 3, Have potential end users join CC and join key decision makings 4, A convinced trust model...

**Comment by fitzthum** [comment]
Thanks for reviewing. We will come back to these requirements, particularly the requirements for incubation, frequently.
