### ISSUE TITLE
[CNCF] Understand the license allowlist

### ISSUE THREAD

**Issue by magowan** [confidential-containers/community#16]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) that this issue will track:*

* [ ] *Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist*
* [ ] *Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)*

**Comment by magowan** [comment]
We need to identify third party dependencies for each repository and the licenses associated with them.
Any that are non Apache 2.0 need further consideration and checked against the 

There is a later item on the checklist
- Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)
Open question - Can we wait for this to help us identify the licenses we already pull in?
Perhaps we should link this task into this issue?

**Comment by magowan** [comment]
Have reached out to CNCF to see if
the help they offer
- Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

This might be the easiest way to answer the question
But also called out this issue in slack to ask for help from others.

**Comment by peterzcst** [comment]
In addition to a license tool, maintainers of each repo should take a close look at this and assure NO code reuse and NO any build/runtime dependency to any projects that are NOT Apache 2.0 or NOT in the allowed list specified in https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#approved-licenses-for-allowlist

**Comment by magowan** [comment]
Updating wiki page here -> https://github.com/confidential-containers/community/wiki/CNCF-Fossa
with section for initial scan info for repositories

**Comment by magowan** [comment]
I believe we as a project understand the license allowlist and we now have Fossa License scanning in place for our projects.

**Comment by magowan** [comment]
For Kata they have
GitHub action to ensure any new file added follows an expected license.
or rust, they can use cargo-deny to scan dependency code license.
