### ISSUE TITLE
[CNCF] Review the online programs guidelines

### ISSUE THREAD

**Issue by magowan** [confidential-containers/community#17]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) that this issue will track:*

* [ ] *Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md*

**Comment by magowan** [comment]
Key point regarding CNCF Online Programs Guidelines
- Sandbox projects cannot host a livestream.

Perhaps the main interest to us in short term :
## YouTube Playlist submission
Submit pre-recorded content (must be relevant to the last six months and can include previous KubeCon presentations) to our curated theme playlists on YouTube via Google Form

**Comment by magowan** [comment]
Welcome thoughts on how we can use the programs offered
and I think we should discuss what we could submit to the Youtube channel in future

**Comment by ariel-adam** [comment]
Reviewed 

This is our current youtube channel: https://www.youtube.com/channel/UCX_0P-ZX2SpvAi05q1XSM4w

**Comment by fidencio** [comment]
Reviewed.
https://github.com/cncf/foundation/blob/main/online-programs-guidelines.md#online-programs-content-guidelines and https://github.com/cncf/foundation/blob/main/online-programs-guidelines.md#submit-to-participate-in-online-programs--deadlines should always be in mind so we don't miss any opportunity on advertising the significant progress we make on one or another area of the project.

**Comment by peterzcst** [comment]
Reviewed.

**Comment by fitzthum** [comment]
Okay, CNCF Online Programs seem like a big opportunity to promote this project. Producing good content is not trivial, but at least we now seem to understand the sort of things that are required.
