### ISSUE TITLE
[CNCF] Review trademark guidelines 

### ISSUE THREAD

**Issue by ariel-adam** [confidential-containers/community#19]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) that this issue will track:*

* [ ] * Understand the [Linux foundation trademark guidelines](https://www.linuxfoundation.org/trademark-usage/)*

This is a statement of The Linux Foundation’s trademarks and its policy and guidelines relating to use of trademarks owned by The Linux Foundation and used by projects under The Linux Foundation
...
### Rules and Policies Applicable to Marks Owned by The Linux Foundation (on top of generally applicable rules):

- Use the full form of any trademarks (e.g., “The Linux Foundation”) in the first reference in all documents of mass communication, including marketing collateral and web pages.  You may then use any abbreviated or short form references (e.g. “TLF”) within the same the document where the full form has already been used.
- Use The Linux Foundation’s trademarks in a form that distinguishes them from the text around them, such as by capitalization, bold or italic fonts, or with quotation marks. Any use of registered trademarks as indicated in The Linux Foundation’s Trademark List at https://www.linuxfoundation.org/trademark-list/ should include the ® symbol immediately after the first usage (e.g., “The Linux Foundation® projects develop open source….”). Any use of unregistered trademarks as listed in the Trademark List should include a TM immediately after the first usage (e.g., “The Core Infrastructure Initiative TM community seeks to secure….”)
- Do not use The Linux Foundation trademarks in a manner that would disparage The Linux Foundation or its projects (e.g., untruthful advertising, false/misleading promotional materials, etc.).
- Do not use a The Linux Foundation logo on the cover of a book or magazine without written permission from The Linux Foundation.
- Do not use The Linux Foundation trademarks more prominently than your own company, product or service name.
- Do not use a logo of The Linux Foundation on posters, brochures, signs, websites, or other marketing materials to promote your events, products or services without written permission from The Linux Foundation.
- Do not refer to a product or service as being certified under any of The Linux Foundation’s marks unless your company has successfully undergone the requisite compliance testing and has explicit authorization to use such terms from The Linux Foundation.
- Do not attempt to claim or assert any ownership rights in any mark of The Linux Foundation and do not attempt to register any The Linux Foundation trademark as a trademark, trade name, domain name, or “doing business as” name, alone or (unless specifically licensed) in combination with your own trademarks.

**Comment by c3d** [comment]
FYI, I reviewed this last Friday, it seems relatively basic. What does it take to close the issue?

**Comment by larrydewey** [comment]
Reviewed. This all seems quite reasonable.

**Comment by bpradipt** [comment]
Reviewed.

**Comment by fidencio** [comment]
Reviewed.

**Comment by peterzcst** [comment]
Reviewed and it's basic and reasonable

**Comment by fitzthum** [comment]
Yup, this seems pretty straightforward. We are already conforming to these guidelines, but let's continue to use common sense and thorough review.
