### ISSUE TITLE
[CNCF] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io

### ISSUE THREAD

**Issue by magowan** [confidential-containers/community#21]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) that this issue will track:*

* [ ] *Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io/*
* [ ] *Ensure the [logo has been submitted to CNCF](https://github.com/confidential-containers/community/issues/23)* before moving forward

**Comment by magowan** [comment]
Git Hub repo for pull request is here -> https://github.com/cncf/landscape

Should we resolve the artwork step first (Submit a pull request to https://github.com/cncf/artwork)
Since whatever gets accepted there is what we should use for landscape?


first to

**Comment by fitzthum** [comment]
We have interests in a few different areas, but I suspect that we mainly fall under `Security & Compliance`.  Do we need to wait for us to get all the different versions of the logo pushed over to the CNCF before we can make a PR here? Can we upload our Logo from somewhere else?

**Comment by ariel-adam** [comment]
What is still remaining to do on this topic?

**Comment by magowan** [comment]
Had some problems with my github access key but fixed that now.
Pull request is here -> https://github.com/cncf/landscape/pull/2559

**Comment by magowan** [comment]
You can see the PR generated picture here -> https://deploy-preview-2559--landscape.netlify.app/
:-)

**Comment by magowan** [comment]
Please take a look at ->https://deploy-preview-2559--landscape.netlify.app/?selected=confidential-containers
Two considerations from pull request template

- Are you only including a repo_url if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.

I opted for https://github.com/confidential-containers/documentation but we can change this?

- Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
We have added stars to our projects? Perhaps we need to encourage people to add them?

**Comment by ariel-adam** [comment]
@magowan is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?
