### ISSUE TITLE
[CNCF] Transfer any trademark and logo mark assets over to the LF

### ISSUE THREAD

**Issue by ariel-adam** [confidential-containers/community#25]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) that this issue will track:*

* [x] *Transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements*

**Comment by ariel-adam** [comment]
I will need to check with Amye how and to who do we submit this PDF (and who needs to sign it :-)).
Can anyone think of any additional trademarks aside from the logo (maybe the name)?

**Comment by larrydewey** [comment]
Reviewed

**Comment by bpradipt** [comment]
Reviewed..

**Comment by fidencio** [comment]
Reviewed.

**Comment by peterzcst** [comment]
Reviewed

**Comment by amye** [comment]
Reopen please! You'll want the 'non registered trademarks' from https://github.com/cncf/foundation/tree/main/agreements -- I will work with you on who needs to sign!

**Comment by fitzthum** [comment]
Form as signed and accepted.
