### ISSUE TITLE
[CNCF] Services for CNCF projects

### ISSUE THREAD

**Issue by ariel-adam** [confidential-containers/community#26]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) tracked by this issue

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) that this issue will track:*

* [ ] *confirm maintainers have read https://www.cncf.io/services-for-projects/*

**Comment by ariel-adam** [comment]
Note that since we are a sandboxed project we are low in the food chain of getting services ;-)

**Comment by ariel-adam** [comment]
If I don't get the person who previously helped us with the COCO logo I will ask their help for creating the multiple logos for the project

**Comment by ariel-adam** [comment]
@wainersm @stevenhorsman can you go over the continues integration section in this document? It seems we may be able to get some services from the CNCF on that

**Comment by sameo** [comment]
I confirm I have read the https://www.cncf.io/services-for-projects/ page.

**Comment by fitzthum** [comment]
See #10

**Comment by ariel-adam** [comment]
Closing this issue since it's a duplicate of https://github.com/confidential-containers/community/issues/10
