### ISSUE TITLE
[CNCF] Ensure your project meets the CNCF IP Policy

### ISSUE THREAD

**Issue by sameo** [confidential-containers/community#27]
We need to ensure we meet the CNCF IP policy:

* [x] Trademark and logo assets transferred to the CNCF. ** WIP, See https://github.com/confidential-containers/community/issues/25 **
* [x] Each project shall determine whether it will require use of an approved CNCF CLA. **We do not require a Contributor License Agreement**
* [x] All new inbound code contributions to the CNCF shall be (i) accompanied by a Developer Certificate of Origin and (ii) made under the Apache License, Version 2.0. ** DCO check is now enforced on all CC PRs ** 
* [x] All outbound code will be made available under the Apache License, Version 2.0. **See https://github.com/confidential-containers/community/blob/main/CONTRIBUTING.md**
* [x] All projects evaluated for inclusion in the CNCF shall be completely licensed under an OSI-approved open source license. If the license for a project included in CNCF is not Apache License, Version 2.0, approval of the Governing Board shall be required. ** See https://github.com/confidential-containers/community/blob/main/CONTRIBUTING.md **
* [x] All documentation will be received and made available by the CNCF under the Creative Commons Attribution 4.0 International License.
* [x] If an alternative inbound or outbound license is required for compliance with the license for a leveraged open source project or is otherwise required to achieve the CNCF’s mission, the Governing Board may approve the use of an alternative license for inbound or outbound contributions on an exception basis. ** We are not looking at an alternative license**

### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) tracked by this issue

* [x] *Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy*

**Comment by magowan** [comment]
Since there is a separate checkbox for 
**Transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements**
which we can leave open for now (#25)

I think we can close this issue and tick off
**Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy**
