### ISSUE TITLE
Identify and detail more non-TEE tests

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/community#3]
We aim to implement Kata Containers specifics tests for Confidential Containers for features which doesn't necessarily involves specialized hardware (i.e. non-TEE tests).

One example of non-TEE specific feature is the *service_offload* of the *kata-agent* that allows to pull the container image entirely in the guest. A test for that feature has been implemented in https://github.com/kata-containers/tests/issues/4509 already, but there are more features like that we should be implementing tests for running on CI.

This, this issue is about identifying and detailing as much as possible the non-TEE test cases. Please share your ideas and comments here.

Note: here we are talking about integration/functional tests; unit tests are out of scope.

----

The list of tests identified along with priorities and owners (Work in Progress):

| ID | Test | Category | Tags | Priority | Owners |  Issue | Notes |
| -- | ---------- | ------- |  ------ | ------- | ------ |  ----- | ----- | 
| I1| Test we can use crictl to create a Kata CC pod by pulling an unencrypted image inside the guest | Image pull | unencrypted, crictl, containerd |  | @wainersm  |  https://github.com/kata-containers/tests/issues/4509 | ----- |
|  I2 | Test we can use Kubernetes to create a Kata CC pod by pulling an unencrypted image inside the guest | Image pull | unencrypted, k8s | High | @stevenhorsman  |  https://github.com/kata-containers/tests/issues/4557  | ----- |
| I3 | Test we can use Kubernetes to create a Kata CC pod by pulling the encrypted ssh demo sample image inside the guest using an offline fs kbc | Image pull | encrypted, k8s, demo | High | @stevenhorsman  |  https://github.com/kata-containers/tests/issues/4685 | ----- |
| I4 | Test that we can create a Kata CC pod by pulling a sample signed, unencrypted image, from an protected registry, inside the guest | Image pull | unencrypted, signed, protected | High? | @wainersm |  https://github.com/kata-containers/tests/issues/4572 | Needs skopeo |
| I5 | Test that we can create a Kata CC pod by pulling a sample unsigned, unencrypted image, from an unprotected registry, inside the guest | Image pull | unencrypted, unsigned, unprotected | Low? | @wainersm |  https://github.com/kata-containers/tests/issues/4572 | Needs skopeo |
| I6 | Test that we **cannot** create a Kata CC pod by pulling a sample unsigned, unencrypted image, from an protected registry, inside the guest | Image pull | unencrypted, signature, unsigned, protected | Medium? | @wainersm |  https://github.com/kata-containers/tests/issues/4572 | Needs skopeo |
| I7 | Test that we **cannot** create a Kata CC pod by pulling a sample signed, unencrypted image, from an protected registry but with a incorrect gpg public key, inside the guest | Image pull | unencrypted, unsigned, protected | High? | @wainersm |  https://github.com/kata-containers/tests/issues/4572 | Needs skopeo |
| A1|  Check that when a Kata CC pod is created with an agent api config that doesn't restrict anything that the endpoints work |  Agent API |  ----  | Low? | @wainersm |  https://github.com/kata-containers/tests/issues/4676 | ----- |
| A2 | Check that when a Kata CC pod is created with an agent api config that blocked certain endpoints that requests to these are rejected |  Agent API |  ----  | High? | @wainersm |  https://github.com/kata-containers/tests/issues/4676 | ----- |
| C3 | Test pulling an image from an authenticated registry directly with an agent-ctl request | Agent CTL | cli | Low? | ------ |  TBD | ----- |

**Priorities**:
 * High - must have on CCv1
 * Medium - nice to have on CCv1
 * Low - can be deferred to CCv2

**Comment by wainersm** [comment]
The document [how-to-build-and-test-ccv0](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-build-and-test-ccv0.md) document maintained by @stevenhorsman is very good source of test cases ideas. As well as the confidential containers [demos](https://github.com/confidential-containers/documentation/tree/main/demos). What else?

@sameo @c3d @stevenhorsman @fidencio - do you have ideas?  Could you please chime in others as I don't know who else should be involved.

**Comment by wainersm** [comment]
Today I I stumbled onto [this spreadsheet](https://docs.google.com/spreadsheets/d/1M_MijAutym4hMg8KtIye1jIDAUMUWsFCri9nq4dqGvA/edit#gid=0&fvid=1397558749) used to list and track progress of CCv0 features. Great! It gives me more ideas for tests...

**Comment by fitzthum** [comment]
A few negative tests come to mind, like trying to use one of the agent endpoints that is blocked (i.e. exec). You might try pulling and running an encrypted image without providing the necessary secrets. I don't know how useful these are for development, but they might help tell the story of what we are trying to do.

**Comment by wainersm** [comment]
> Yep - I think there are a few test scenarios we could do on non-TEE, that you've probably already come across:
> ### E2E Image pull tests
> 
>     * Test we can use `crictl` to create a Kata CC pod by pulling an unencrypted image inside the guest
>       
>       * Check that the image was pulled on the guest, and more importantly that is wasn't pulled on the host
> 
>     * Test we can use Kubernetes to create a Kata CC pod by pulling an unencrypted image inside the guest
>       
>       * Check that the image was pulled on the guest, and more importantly that is wasn't pulled on the host
> 
>     * Test we can use Kubernetes to create a Kata CC pod by pulling the encrypted ssh demo sample image inside the guest using an offline fs kbc
>       
>       * Check that the image was pulled on the guest, and more importantly that is wasn't pulled on the host
>         
>         * Check that it works when we use the correct key and the image is able to be decrypted
>       * Check the overall pull operation fails and the image can't be decrypted if there offline fs kbc file is missing
>       * Check the overall pull operation fails and the image can't be decrypted if there offline fs kbc file has the wrong key
> 
>     * Test that we can create a Kata CC pod by pulling a sample signed, unencrypted image inside the guest
>       
>       * **This requires that `skopeo` is added the guest image as it doesn't work with the current rust implementation, but is part of `image-rs`**

Hijacking this issue a little bit... will `skopeo` support be removed after image-rs and other pieces are ready?

Currently, IIUC, if the skopeo binary is present in the guest then it is used. Or it is configurable and I missed it?

>       * _I've realised writing this that I've never actually tested this end to end, but only against the agent, but I can't immediately think of a reason that it wouldn't work_

By e2e you mean really create the container? If yes, is it expected to work if we create it with crictl + containerd?

I saw that in the `ccv0.sh` script you've used the `agent-ctl` which, IIUC, is a tool for development purpose only. 
 
>       * Test that the sample signed image from a 'protected registry' can be correctly pulled
>       * Test that an unsigned image can be correctly pulled from an unauthenticated registry
>       * Test that a Kata CC pull of the sample unsigned image from a 'protected registry' is rejected
>       * Test that a  Kata CC pull of the sample signed image with an incorrect gpg pulbic key from a 'protected registry' is rejected
> 

Above test cases are likely to be implemented together/same person.

> 
> ### Agent API tests
> 
>     * _I suspect that we'll just need to pick a couple of key ones, like `exec` as Tobin suggests rather than covering them all_

I think so. BTW, thanks @fitzthum for your input in this issue!

> 
>     * Check that when a Kata CC pod is created with an agent api config that doesn't restrict anything that the endpoints work
> 
>     * Check that when a Kata CC pod is created with an agent api config that blocked certain endpoints that requests to these are rejected
> 
> 
> ### Agent Component specific test (not available for e2e testing yet)
> 
>     * Test pulling an image from an authenticated registry directly with an agent-ctl request
>       
>       * Check that the image is pulled successfully with correct credentials
>       * Check at the image pull is rejected when incorrect credentials are used
> 
> 
> @wainersm - Those are the test cases that I can immediately think of. There are definitely different categories of priority in the implementation of them and I'm sure I must have missed lots, but I hope it is somewhat useful.

That list helped A LOT! In fact, if you see the description of this issue you gonna see I converted your list into the table.

Honestly I don't think we should commit to deliver more than that on CCv1. I will certainly be implement test cases but I don't be able to deliver all; and it is still not clear who else will be helping on show-me-the-code tasks.

You can also note that I put priorities on the use cases. They are just guesses (this explain the question marks), and my rationale was: "the close to a truly confidential container use case, the higher should be the priority". Also the priorities are simple "must have" (high), "nice to have" (medium) and "defer to CCv2" (low).
 
I didn't create further issues. IMO the list is good enough and if you all agree I can start chasing people to help out. And then each owner create their issues...

**Comment by stevenhorsman** [comment]
> Hijacking this issue a little bit... will `skopeo` support be removed after image-rs and other pieces are ready?

Yes, when `image-rs` is included `skopeo` will be gone for good (along with `umoci`). I included the skopeo piece as we could begin to write those tests now with `skopeo` before waiting for `image-rs` (and to provide regression testing for `image-rs`

> Currently, IIUC, if the skopeo binary is present in the guest then it is used. Or it is configurable and I missed it?

That's correct. Are 'configuration' is just whether we set `SKOPEO="YES"` in the call to `rootfs.sh` and have it added to the guest image, and as you say, if it is there it will be used.

> > ```
> >   * _I've realised writing this that I've never actually tested this end to end, but only against the agent, but I can't immediately think of a reason that it wouldn't work_
> > ```
> 
> By e2e you mean really create the container? If yes, is it expected to work if we create it with crictl + containerd?
> I saw that in the `ccv0.sh` script you've used the `agent-ctl` which, IIUC, is a tool for development purpose only.

Sorry for the confusion. By not testing e2e I mean that I'd only tested the `pull_image` bit, by either calling the agent directly via `agent-ctl`, or using `ctr shim`. By e2e I mean creating a pod & container using `crictl`, or Kubernetes, which I've not tested manually before, but *think* it should work. The reason that I used `agent-ctl` was that the agent endpoints were ready months before the containerd-shim-v2 pieces. I agree that it is mostly for development, but I can see a scenario in which we want to merge the guest stuff into `main` before the host side is ready (due to the containerd fork complications), so we might still want to utilise `agent-ctl` for testing if this happens. Also some functionality (e.g. pulling from an authenticated registry) isn't supposed e2e, but only from the agent endpoint. I think I marked these types of tests as 'component' 


> > ```
> >   * Test that the sample signed image from a 'protected registry' can be correctly pulled
> >   * Test that an unsigned image can be correctly pulled from an unauthenticated registry
> >   * Test that a Kata CC pull of the sample unsigned image from a 'protected registry' is rejected
> >   * Test that a  Kata CC pull of the sample signed image with an incorrect gpg pulbic key from a 'protected registry' is rejected
> > ```
> 
> Above test cases are likely to be implemented together/same person.
> 

Agreed. There are different paths of the same test, so that makes sense

#### Priority comments

Generally good, but here are a few thoughts:

*i2* - I assume that you've marked this scenario as Medium due the overlap with i3? If so I think there is an argument that i2 is a simpler version of i3, and therefore a step in the direction of i3, so think there is still value.
Otherwise IMHO Kubernetes seems to be much more widely used than crictl, so we’d want coverage of it. I'd be tempted to have is as high as it would allow us to get some Kubernetes basics in without worrying about the encryption complications.

*i5* - Until we have the ability to supply a custom policy.json through the attestation agent, in principle this is important to check that we don’t lock people out of pulling unsigned images accidentially, however I think the scenario is currently covered by i1&i2, so definitely low/won't do for now.

*c3* - I’d maybe maybe like to see c3 bumped to medium, as although it is a ‘component test’ we can’t test the function any other way, so it provides good stand alone value

**Comment by stevenhorsman** [comment]
@wainersm - as discussed yesterday, can you put me as the contact for i2, bump the priority to high and add a link to https://github.com/kata-containers/tests/issues/4557 please? Thanks!

**Comment by wainersm** [comment]
> @wainersm - as discussed yesterday, can you put me as the contact for i2, bump the priority to high and add a link to [kata-containers/tests#4557](https://github.com/kata-containers/tests/issues/4557) please? Thanks!

Done.

**Comment by wainersm** [comment]
Hi @stevenhorsman , yesterday I was looking at the agent's source code then I was wondering if it would be enough to have an unit test to cover the case A2. Maybe implemented on the agent's rpc module (https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/rpc.rs#L1884).

Btw, do you know where (if any) is the documentation about agent API configuration? I couldn't find any information... :(

**Comment by wainersm** [comment]
> > Hi @stevenhorsman , yesterday I was looking at the agent's source code then I was wondering if it would be enough to have an unit test to cover the case A2. Maybe implemented on the agent's rpc module (https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/rpc.rs#L1884).
> 
> Hey @wainersm - This is a key 'confidential computing' security feature to stop the CSP admin from being able to access the workload providers pod, so I think it would be worth having the 'end-user' integration test rather than just the unit test. I think adding a unit test to that file would be good to check `is_allowed`, but as the function is already part of the `main` branch it's lower down my personal wish list for new unit tests!
>

Good point. If I find some time maybe I can pick that work.
 
> > Btw, do you know where (if any) is the documentation about agent API configuration? I couldn't find any information... :(
> 
> I'm not sure of any 'proper' documentation for this (Which is probably another gap we want to close). I just used the issue: [kata-containers/kata-containers#1837](https://github.com/kata-containers/kata-containers/issues/1837) and PR: [kata-containers/kata-containers#2517](https://github.com/kata-containers/kata-containers/pull/2517) when I was trying to understand it.

Trying to document it here: https://github.com/kata-containers/kata-containers/pull/4016

**Comment by wainersm** [comment]
Hi @stevenhorsman ! I'm assigning to myself the implementation of tests A1 and A2; I've already a prototype.

**Comment by stevenhorsman** [comment]
@wainersm - I've created https://github.com/kata-containers/tests/issues/4685 to cover i3. Can you add it to the description please (and also please review it) when you get the chance? Thanks!

**Comment by wainersm** [comment]
> @wainersm - I've created [kata-containers/tests#4685](https://github.com/kata-containers/tests/issues/4685) to cover i3. Can you add it to the description please (and also please review it) when you get the chance? Thanks!

Hi @stevenhorsman , just update the description. thanks!

**Comment by wainersm** [comment]
Closing this as the high and medium tests were implemented.
