### ISSUE TITLE
ci: create Intel TDX CI pipeline for CCv0+QEMU+TDVF

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/community#32]
@peterzcst and the Intel team is ready to integrate the first CI pipeline into Kata CI for running TEE specific tests. The test environment should be prepared with CCv0, QEMU and TDX Virtual Firmware (TDVF).

They will be running the tests in one of their labs (so behind the firewall) as discussed in #4.

I'm creating this issue to track the work needed and progress.

Related to #2 

Cc @peterzcst @arronwy

**Comment by wainersm** [comment]
@arronwy sent some pull requests to implement prior changes:

[CCv0: agent: Support https_proxy config for image download in guest](https://github.com/kata-containers/kata-containers/pull/3957)
[ci: Add TEE_TYPE flag for TEE enabled kernel/hypervisor](https://github.com/kata-containers/tests/pull4668)
[CCv0: Enable TEE related CI behind firewall](https://github.com/kata-containers/tests/pull/4662)

**Comment by peterzcst** [comment]
Kata upstream already generated the access token for the TDX Jenkins server behind firewall. 
We created a webhook to receive events through a proxy and post build results.  And the webhook is added in kata-containers project

**Comment by wainersm** [comment]
Hi @peterzcst , on recent pull requests opened for `CCv0`branch the post build results weren't displayed. Is the pipeline running?

**Comment by arronwy** [comment]
> 

@wainersm  We are waiting the PRs to enable TEE related CI behind firewall to be merged, after that, the pipeline will be enabled by default.

**Comment by wainersm** [comment]
> Hi @wainersm , thanks for your help, I think we can close this issue since this CI pipeline is added and verified by this PR: [kata-containers/kata-containers#4221](https://github.com/kata-containers/kata-containers/pull/4221) (jenkins-ci-tdx-x86_64-cc_cri_containerd) and my test PR both works: [kata-containers/kata-containers#4146](https://github.com/kata-containers/kata-containers/pull/4146)
> 

Thanks for the heads up @arronwy ! I will close this issue.

> Next we will monitor the stability of this pipeline.

One more thing @arronwy, would you mind to share the steps, configurations...etc you used to setup the job? I'd like to have it documented somewhere so that others vendors could bring their on systems to our CI if they wish to. You can send me the raw material then I can nicely format the text and open the pull request.
Thanks!

**Comment by arronwy** [comment]
> > Hi @wainersm , thanks for your help, I think we can close this issue since this CI pipeline is added and verified by this PR: [kata-containers/kata-containers#4221](https://github.com/kata-containers/kata-containers/pull/4221) (jenkins-ci-tdx-x86_64-cc_cri_containerd) and my test PR both works: [kata-containers/kata-containers#4146](https://github.com/kata-containers/kata-containers/pull/4146)
> 
> Thanks for the heads up @arronwy ! I will close this issue.
> 
> > Next we will monitor the stability of this pipeline.
> 
> One more thing @arronwy, would you mind to share the steps, configurations...etc you used to setup the job? I'd like to have it documented somewhere so that others vendors could bring their on systems to our CI if they wish to. You can send me the raw material then I can nicely format the text and open the pull request. Thanks!

Sure, I just sent the slides and steps to you through email :-)
