### ISSUE TITLE
Document communication channels

### ISSUE THREAD

**Issue by dcmiddle** [confidential-containers/community#35]
From the `Basics` / `Other` section of https://bestpractices.coreinfrastructure.org/en/projects/5719

_The project MUST have one or more mechanisms for discussion (including proposed changes and issues) that are searchable, allow messages and topics to be addressed by URL, enable new people to participate in some of the discussions, and do not require client-side installation of proprietary software._

Add communications references to .github and community repos once the communication channels are finalized.
.github repo

- [x] meetings
- [x] slack
- [ ] mail list

community repo (these could be satisfied by reference to the .github repo or vice versa)

- [ ] meetings
- [ ] slack
- [ ] mail list

**Comment by ariel-adam** [comment]
@dcmiddle is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by dcmiddle** [comment]
We decided against a mail list, or at least we never decided to use a mail list.
Regardless we have satisfied the criteria with documenting where to find the meetings, slack, and of course having github issues.
