### ISSUE TITLE
Document Working build system

### ISSUE THREAD

**Issue by dcmiddle** [confidential-containers/community#38]
From https://bestpractices.coreinfrastructure.org/en/projects/5719#quality

_If the software produced by the project requires building for use, the project MUST provide a working build system that can automatically rebuild the software from source code.
The project SHOULD be buildable using only FLOSS tools._

See also
https://github.com/confidential-containers/community/issues/2

**Comment by ariel-adam** [comment]
@dcmiddle is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by dcmiddle** [comment]
Updated badge documentation:
Each component as automated builds. There is a documented process for cutting releases. https://github.com/confidential-containers/community/issues/74
Each repo has a Makefile and/or Cargo.toml.
