### ISSUE TITLE
Document Automated Test Suite

### ISSUE THREAD

**Issue by dcmiddle** [confidential-containers/community#39]
From https://bestpractices.coreinfrastructure.org/en/projects/5719#quality

_The project MUST use at least one automated test suite that is publicly released as FLOSS (this test suite may be maintained as a separate FLOSS project). The project MUST clearly show or document how to run the test suite(s) (e.g., via a continuous integration (CI) script or via documentation in files such as BUILD.md, README.md, or CONTRIBUTING.md)_

_It is SUGGESTED that the project implement continuous integration (where new or changed code is frequently integrated into a central code repository and automated tests are run on the result)._

See also
https://github.com/confidential-containers/community/issues/2

**Comment by ariel-adam** [comment]
@dcmiddle is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by dcmiddle** [comment]
Reviewing the status of repositories at the end of the v0.4.0 release cycle it looks like those components that are part of the release satisfy a basic CI. The only one I'm not sure about is attestation-agent.

Repos in the v0.4.0 release with CI condition `met`:
- [ ] attestation-agent[0]
- [x] enclave-cc (partial with additional in progress [1])
- [x] image-rs 
- [x] ocicrypt-rs
- [x] operator (various issues about getting away from kata's CI)
- [x] simple-kbs
- [x] td-shim

Not part of the v0.4.0 release are kbs, attestation-service and cloud-api-adapter repos. Attestation-service and cloud-api-adapter appear to have CI coverage, whereas kbs seems to be lacking tests beyond linting.

[0] Attestation-agent status:

> ```
> $ grep -r 'mod tests' *
> app/src/grpc/keyprovider/message.rs:mod tests {
> app/src/grpc/keyprovider/mod.rs:mod tests {
> sample_keyprovider/src/enc_mods/offline_fs_kbs/mod.rs:mod tests {
> sample_keyprovider/src/enc_mods/offline_fs_kbs/common.rs:pub mod tests {
> src/kbc_modules/offline_sev_kbc/mod.rs:mod tests {
> src/kbc_modules/offline_fs_kbc/mod.rs:mod tests {
> src/kbc_modules/offline_fs_kbc/common.rs:pub mod tests {
> ```
> notably absent are both the cc-kbc and eaa-kbc. 
> 

[1] https://github.com/confidential-containers/enclave-cc/pull/97
[2]https://github.com/confidential-containers/community/issues/69, https://github.com/confidential-containers/community/issues/67, https://github.com/confidential-containers/community/issues/32 (closed)
see also https://github.com/confidential-containers/community/issues/52

**Comment by dcmiddle** [comment]
Attestation-agent patched for EAA KBC. https://github.com/confidential-containers/attestation-agent/pull/146. Thanks @jialez0 
enclave-cc now with self-hosted runner for SGX HW tests. thanks @mythi and @huliucheng1

Updated badge documentation to include..
All repos that are part of a CoCo release have working CI calling test suites as of v0.4.0 (with some expanded coverage for self-hosted runners for hardware specific testing by v0.5.0 or earlier).
