### ISSUE TITLE
CI should include lint checks and maximally strict warnings

### ISSUE THREAD

**Issue by dcmiddle** [confidential-containers/community#41]
From https://bestpractices.coreinfrastructure.org/en/projects/5719#quality

The project MUST enable one or more compiler warning flags, a "safe" language mode, or use a separate "linter" tool to look for code quality errors or common simple mistakes, if there is at least one FLOSS tool that can implement this criterion in the selected language.

The project MUST address warnings.

It is SUGGESTED that projects be maximally strict with warnings in the software produced by the project, where practical. 

See also https://github.com/confidential-containers/community/issues/2

**Comment by ariel-adam** [comment]
@dcmiddle is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by dcmiddle** [comment]
Verified linting checks in CI across all repos that shipped in v0.4.0; Badge documentation updated accordingly.
