### ISSUE TITLE
Identify and detail TEE tests

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/community#5]
We split the testing efforts for CCv1 in two (non-TEE vs TEE) CC specific tests to make the work manageable. Also non-TEE tests can be implemented firstly as they don't rely on TEE hardware, hardware requirements which we are still being discussing in #4. The list of non-TEE tests has been discussed on #3 , so this issue is a place to discuss TEE specific tests likewise.

One example of TEE specific feature is the confidential guest (property `confidential_guest=true` set on kata's `configuration.toml`) which utilizes hardware technologies such as AMD SEV to achieve memory and cpu-state encryption.

Please, share the test cases you think we should be implementing for TEE features.

**Comment by wainersm** [comment]
Regarding the TEE test I mentioned on the description; it has been implemented for TDX in https://github.com/kata-containers/tests/pull/4584

**Comment by sphrasavath** [comment]
@wainersm Suggestions on how to handle this scenario below:
CC v0 for SEV depends on the following PR, https://github.com/kata-containers/kata-containers/pull/3025,  which has not yet been merged into kata-container main.  We can define a sev functional test and as part of the enable_confidential_computing or setup step kata-runtime would need to be rebuild with pr#3025.  
Is this acceptable?  Suggestions or comments?

**Comment by wainersm** [comment]
Hi @sphrasavath !

> @wainersm Suggestions on how to handle this scenario below: CC v0 for SEV depends on the following PR, [kata-containers/kata-containers#3025](https://github.com/kata-containers/kata-containers/pull/3025), which has not yet been merged into kata-container main. We can define a sev functional test and as part of the enable_confidential_computing or setup step kata-runtime would need to be rebuild with pr#3025. Is this acceptable? Suggestions or comments?

We are still developing the confidential containers features for Kata Containers in a branch called [`CCv0`](https://github.com/kata-containers/kata-containers/tree/CCv0).  At some point that branch will be merged into kata's `main` though.

So for now, your sev functional test should be targeting the [`CCv0` branch the tests repository](https://github.com/kata-containers/kata-containers/tree/CCv0). We have jobs on Kata's Jenkins to build and run the tests from those `CCv0` branches.

I suggest you to open a pull request with your test code as is (assuming it is functional) If you feel comfortable. Put the `wip` label on the PR. Then I can start reviewing and give it a try. What do you think?

**Comment by wainersm** [comment]
Closing as this was apart of the 1st release.
