### ISSUE TITLE
Move `ocicrypt-rs` to the Confidential Containers organization

### ISSUE THREAD

**Issue by sameo** [confidential-containers/community#7]
The [`ocicrypt-rs`](https://github.com/containers/ocicrypt-rs) was created and developed to support the CC [Attestation Agent](https://github.com/confidential-containers/attestation-agent). Since the CC project is the main consumer and maintainer of `ocicrypt-rs`, I think it would make sense and be easier from a logistical stand point to now move it to the CC org.

@lumjjb ((`ocicrypt`)[https://github.com/containers/ocicrypt] original author and a github.com/containers org admin) has agreed on the move, provided that we document the link between the 2 repos (`ocicrypt` and `ocicrypt-rs) in the README.

**Comment by peterzcst** [comment]
Fully agree. It makes sense to host ocicrypt-rs in CC. It's not used only by current CC but also coming enclave-cc and even more CC related projects.

**Comment by jiangliu** [comment]
Agreed!

**Comment by jiazhang0** [comment]
Looks good to me.

**Comment by sameo** [comment]
Repo moved at https://github.com/confidential-containers/ocicrypt-rs
