### ISSUE TITLE
CNCF onboarding

### ISSUE THREAD

**Issue by sameo** [confidential-containers/community#8]
On-boarding the CC project to the CNCF is tracked by the latter through https://github.com/cncf/toc/issues/799.
As a community we have to work in order to tick all the boxes from that issue before becoming an official CNCF Sandbox project.

Anyone in the community is welcome to participate to that effort, and in order to do so I propose to follow those 2 steps:

1. Open an [issue](https://github.com/confidential-containers/community/issues/new?assignees=&labels=cncf-onboarding&template=cncf-onboarding.md&title=%5BCNCF%5D) in the community repo, describing which parts of the CNCF onboarding effort the issue will track. There are dedicated issue template  and label for that, please follow them.
2. Open one or several PRs (Most *likely* in the community, documentation or .github repos) and add  `Fixes #<your_issue>` to the commit messages

Once the issue is closed, we will update the CNCF issue itself.

Many thanks in advance for your time and help!

**Comment by dcmiddle** [comment]
@sameo I think we are done with this issue now?
