### ISSUE TITLE
[Release] Check list for v0.5.0

### ISSUE THREAD

**Issue by jepio** [confidential-containers/community#80]
# v0.5.0

## Code freeze

- [x] - 1. Update image-rs to use the latest commit from ocicrypt-rs (@wainersm)
        
        * https://github.com/confidential-containers/image-rs/blob/main/Cargo.toml
          * Change the revision
          * Run `cargo update -p ocicrypt-rs`
        * Opened: https://github.com/confidential-containers/image-rs/pull/138
- [x] - 2. Update image-rs to use the latest commit from attestation-agent (@wainersm)

        * https://github.com/confidential-containers/image-rs/blob/main/Cargo.toml
          * Change the revision
          * Run `cargo update -p attestation_agent`
        * Opened: https://github.com/confidential-containers/image-rs/pull/138

- [x] - 3. Update Enclave CC to use the latest commit from image-rs (@wainersm)

        * https://github.com/confidential-containers/enclave-cc/blob/main/src/enclave-agent/Cargo.toml
          * Change the revision
          * Run `cargo update --manifest-path src/enclave-agent/Cargo.toml -p image-rs`
        Note that you can point to your own fork here, so you don't actually do changes in the other projects
        before making sure this step works as expected.
        * Opened: https://github.com/confidential-containers/enclave-cc/pull/143

- [x] - 4. Update Kata Containers to use the latest commit from image-rs (@wainersm)

        * https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/Cargo.toml
          * Change the revision
          * Run `cargo update -p image-rs`
        Note that you can point to your own fork here, so you don't actually do changes in the other projects
        before making sure this step works as expected.

- [x] - 5. Update Kata Containers to use the latest attestation-agent (@wainersm)

        * https://github.com/kata-containers/kata-containers/blob/CCv0/versions.yaml
          * Change the version

- [x] - 6. Update Kata Containers to use the latest td-shim (@wainersm)

        * https://github.com/kata-containers/kata-containers/blob/CCv0/versions.yaml
          * Change the version

- [x] - 7. Check if there are new changes in the pre install payload script

        * https://github.com/confidential-containers/operator/tree/main/install/pre-install-payload
          * The last commit there must match what's in the following files as preInstall / postUninstall image
            * Enclave CC: https://github.com/confidential-containers/operator/blob/main/config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
            * Kata Containers:
              Note that for Kata Containers, we're looking for the newTag, below the quay.io/confidential-containers/container-engine-for-cc-payload image
              * s390x: https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/s390x/kustomization.yaml
              * x86_64: https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/default/kustomization.yaml

- [x] - 8. Ensure the Operator is using the latest CI builds and that the Operator tests are passsing

        * Enclave CC:
          * SIM: https://github.com/confidential-containers/operator/blob/main/config/samples/enclave-cc/sim/kustomization.yaml
          * HW: https://github.com/confidential-containers/operator/blob/main/config/samples/enclave-cc/base/ccruntime-enclave-cc.yaml
          * Note that we need the quay.io/confidential-containers/runtime-payload-ci registry and enclave-cc-{SIM,HW}-latest tags
        * Kata Containers:
          * s390x: https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/s390x/kustomization.yaml
          * x86_64: https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/default/kustomization.yaml
          Note that we need the quay.io/confidential-containers/runtime-payload-ci registry and kata-containers-latest tag

- [x] - 9. Cut an ocicrypt-rs v<TARGET_RELEASE> release, if changes happened in the project

- [x] - 10. Cut an attestation-agent v<TARGET_RELEASE>, if changes happened in the project

- [x] - 11. Cut an image-rs v<TARGET_RELEASE> release, using the latest release of:

        * ocicrypt-rs (redo step 1, but now using v<TARGET_RELEASE>)
        * attestation-agent (redo step 2, but now using v<TARGET_RELEASE>)

- [x] - 12. Cut a td-shim v<TARGET_RELEASE> release, if changes happened in the project

- [x] - 13. Update Enclave CC to use the released version of image-rs

        * redo step 3, but now using v<TARGET_RELEASE>

- [x] - 14. Update Kata Containers to the latest released version of:

        * image-rs (redo step 4, but now using the v<TARGET_RELEASE>)
        * attestation-agent (redo step 5, but now using the v<TARGET_RELEASE>)
        * td-shim (redo step 6, but now using the v<TARGET_RELEASE>)

- [x] - 15. Update the operator to use the images generated from the latest commit of both Kata Containers and Enclave CC

        * redo step 8, but now targetting the latest payload image generated for Kata Containers and Enclave CC

- [x] - 16. Make sure all the operator tests are passing

- [x] - 17. Cut an Enclave CC release

- [x] - 18. Add a new Kata Containers tag

## Release

- [x] - 19. Update the operator to use the release tags coming from Enclave CC and Kata Containers

        * redo step 8, but now targetting thje latest release of the payload image generated for Kata Containers eand Enclave CC

- [x] - 20. Update the Operator version

        * https://github.com/confidential-containers/operator/blob/main/config/release/kustomization.yaml#L7

- [x] - 21. Cut an operator release

- [x] - 22. Make sure to update the release notes

        * https://github.com/confidential-containers/documentation/tree/main/releases/v<TARGET_RELEASE>.md
        
- [x] - 23. Poke Jens Freimann (jfreiman@redhat.com) to update the release to the OperatorHub

**Comment by jepio** [comment]
I believe the following PRs need to be tested, approved and merged to start the release:
kata-containers:
- [ ] https://github.com/kata-containers/kata-containers/pull/6404
- [ ] https://github.com/kata-containers/kata-containers/pull/6520
tests:
- [ ] https://github.com/kata-containers/tests/pull/5577
- [ ] https://github.com/kata-containers/tests/pull/5582
- [ ] https://github.com/kata-containers/tests/pull/5584
- [ ] https://github.com/kata-containers/tests/pull/5579 (this PR combines the others + has some extra fixes needed)

I'm current running CI of all those PRs together (using depends-on) in:
- https://github.com/kata-containers/kata-containers/pull/6569.

**Comment by Xynnn007** [comment]
Also, this release also includes KBS/AS. We might need the following steps:
- [ ] 1. Cut an attestation-service v<TARGET_RELEASE> and make images for AS and RVPS, if changes happened in the project. 
```
   * https://github.com/confidential-containers/attestation-service
   * Cut a release
   *  Make the image for AS and RVPS
     * docker build -t quay.io/confidential-containers/attestation-service:v<TARGET_RELEASE> -f Dockerfile.as .
     * docker build -t quay.io/confidential-containers/reference-value-provider-service:v<TARGET_RELEASE> -f Dockerfile.rvps .
     * docker push quay.io/confidential-containers/attestation-service:v<TARGET_RELEASE>
     * docker push quay.io/confidential-containers/reference-value-provider-service:v<TARGET_RELEASE>
```

- [ ] 2. Update kbs to use the latest commit from attestation-service, cut a release and make image
```
  * https://github.com/confidential-containers/kbs/blob/main/src/api_server/Cargo.toml
  * Change the revision for the following crates (both use `v<TARGET_RELEASE>`)
     * `as-types`
     * `attestation-service`
  * Make the image
     * docker build -t quay.io/confidential-containers/key-broker-service:v<TARGET_RELEASE> -f docker/Dockerfile.grpc-as .
     * docker push quay.io/confidential-containers/key-broker-service:v<TARGET_RELEASE>
  * Change the image reference in the `docker-compose.yml` file with newly generated images
  * Cut a release
```

**Comment by jepio** [comment]
@Xynnn007 where is the release automation for those container images?

Tagging and syncing up more dependencies and repositories is problematic and unsustainable. This needs a better solution.

**Comment by Xynnn007** [comment]
> @Xynnn007 where is the release automation for those container images?
> 
> Tagging and syncing up more dependencies and repositories is problematic and unsustainable. This needs a better solution.

Yes, you're right. Now we do not have one. Do you have any examples or suggestions? I can start with this, probably after v0.5.0

**Comment by wainersm** [comment]
> I believe the following PRs need to be tested, approved and merged to start the release: kata-containers:
> 
>     * [x]  [agent: add support for ttrpc kata-containers/kata-containers#6404](https://github.com/kata-containers/kata-containers/pull/6404)
> 
>     * [x]  [osbuilder: support cc-kbc for tdx kata-containers/kata-containers#6520](https://github.com/kata-containers/kata-containers/pull/6520)
> 
> 
> tests:
> 
>     * [x]  [Signatures: add resources with new URI scheme kata-containers/tests#5577](https://github.com/kata-containers/tests/pull/5577)
> 
>     * [x]  [ci: Set cc_kbc as the AA_KBC type for TDX kata-containers/tests#5582](https://github.com/kata-containers/tests/pull/5582)
> 
>     * [x]  [SEV: Make SEV tests work with resource URI kata-containers/tests#5584](https://github.com/kata-containers/tests/pull/5584)
> 
>     * [x]  [Signatures: add resources with new URI scheme; PART 2 kata-containers/tests#5579](https://github.com/kata-containers/tests/pull/5579) (this PR combines the others + has some extra fixes needed)
> 
> 
> ssh-demo:
> 
>     * [x]  [ssh-demo: Use KBS URI in demo documentation#114](https://github.com/confidential-containers/documentation/pull/114)
> 
> 
> I'm current running CI of all those PRs together (using depends-on) in:
> 
>     * [CC | agent: add support for ttrpc + dependency on test PR kata-containers/kata-containers#6569](https://github.com/kata-containers/kata-containers/pull/6569).

Hi @jepio ,

All those PR are closed now. Can we start the freeze process? What can I do to help?

**Comment by fidencio** [comment]
@wainersm, what about start with items from 1-5?

**Comment by wainersm** [comment]
> @wainersm, what about start with items from 1-5?

Good idea. Edited the description, put my name on those items.

**Comment by wainersm** [comment]
This is a summary of steps 1-6:
 * attestation-agent commit c939d21
 * ocicrypt-rs had updated attestation-agent to commit c939d21 (https://github.com/confidential-containers/ocicrypt-rs/pull/63)
 * image-rs had updated attestation-agent to commit c939d21 and ocicrypt-rs to commit 55ab22d (https://github.com/confidential-containers/image-rs/pull/138)
 * enclave-cc had updated image-rs to commit b28eaae (https://github.com/confidential-containers/enclave-cc/pull/143)
 * kata-containers had updated image-rs to commit b28eaae, td-shim to commit 10568bab569b and attestation-agent to commit  c939d211fe5ac49771 (https://github.com/kata-containers/kata-containers/pull/6651)

The steps 7 and 8 can be carried out as soon as https://github.com/kata-containers/kata-containers/actions/runs/4693722127 finishes, that is going to generate the new runtime payload (https://quay.io/repository/confidential-containers/runtime-payload-ci?tab=tags) for the operator. @larrydewey

**Comment by fidencio** [comment]
Items 7 and 8 are covered here: https://github.com/confidential-containers/operator/pull/200

**Comment by fidencio** [comment]
ocicrypt-rs release: https://github.com/confidential-containers/ocicrypt-rs/releases/tag/v0.5.0

**Comment by fidencio** [comment]
attestation-agent release: https://github.com/confidential-containers/attestation-agent/releases/tag/v0.5.0

**Comment by fidencio** [comment]
image-rs release with up-to-date tags: https://github.com/confidential-containers/image-rs/releases/tag/v0.5.0

**Comment by fidencio** [comment]
> ocicrypt-rs release: https://github.com/confidential-containers/ocicrypt-rs/releases/tag/v0.5.0

Second try: https://github.com/confidential-containers/ocicrypt-rs/releases/tag/v0.5.1

**Comment by fidencio** [comment]
> image-rs release with up-to-date tags: https://github.com/confidential-containers/image-rs/releases/tag/v0.5.0

Second try: https://github.com/confidential-containers/image-rs/releases/tag/v0.5.1

**Comment by fidencio** [comment]
Enclave CC release was cut: https://github.com/confidential-containers/enclave-cc/releases/tag/v0.5.0

**Comment by fidencio** [comment]
Kata Containers tag has been created: https://github.com/kata-containers/kata-containers/releases/tag/CC-0.5.0

**Comment by fidencio** [comment]
https://github.com/confidential-containers/documentation/blob/main/releases/v0.5.0.md was updated 2 weeks ago.

**Comment by jensfr** [comment]
yep, I'll do that

**Comment by fitzthum** [comment]
Docs are done for v0.5.0. I am holding off on tagging the docs on Monday so that we can change the link to the CAA README to point to main rather than staging.

**Comment by jensfr** [comment]
PR for operatorhub is done and ready to be merged, should happen soon. 
https://github.com/k8s-operatorhub/community-operators/pull/2622

**Comment by fitzthum** [comment]
Documentation tagged now.
