### ISSUE TITLE
[New Project] Create the infra repository 

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/community#90]
## Project Description

This issue is a spin off of  #83.

It should be create an "infra" repository to host common CI code, Github automation, Bots, etc...that is used/deployed by the community to assist on development and release of CoCo.

## GitHub repositories needed

https://github.com/confidential-containers/infra

**Comment by wainersm** [comment]
We already have content for that repository. @mkulke created https://github.com/mkulke/garm-playground for enabling GARM within our repositories.

**Comment by sameo** [comment]
https://github.com/confidential-containers/infra created.
@wainersm you should have received an invite to admin the repo. I *think* you should be able to add more people to the infra team, let me know if that's not the case.
